global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using NavigationViewPopupPanel_IndexOutOfRange.DataContracts;
global using NavigationViewPopupPanel_IndexOutOfRange.DataContracts.Serialization;
global using NavigationViewPopupPanel_IndexOutOfRange.Models;
global using NavigationViewPopupPanel_IndexOutOfRange.Presentation;
global using NavigationViewPopupPanel_IndexOutOfRange.Services.Caching;
global using NavigationViewPopupPanel_IndexOutOfRange.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
